### ISSUE TITLE
[Feature Request] Adding list of types to see members of a group

### ISSUE THREAD

**Issue by eleguns** [Nekogram/Nekogram#10]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I wanna having these buttons for example for filtering members and just see bots.
![Screenshot_20230929_222801](https://github.com/Nekogram/Nekogram/assets/96687447/582811f2-1258-48a3-9845-40ea4c23acb8)

**Comment by tehcneko** [comment]
you can get a decent members list from the info button
