### ISSUE TITLE
[Feature Request] Message Filter

### ISSUE THREAD

**Issue by Fatcavill** [Nekogram/Nekogram#100]
### Is your feature request related to a problem?

There is many custom ads in chats,group,channel

### Describe the solution you'd like

Something like ayugram message filter
Regex+case insensitive support
![Screenshot_2024-06-11-02-14-51-747_com radolyn ayugram](https://github.com/Nekogram/Nekogram/assets/139833732/bb249e5b-e20a-484f-afab-b34205e67be6)

**Comment by tehcneko** [comment]
#114
