### ISSUE TITLE
[Feature Request] Add feature to share files individually

### ISSUE THREAD

**Issue by Lawless0ne** [Nekogram/Nekogram#103]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

To share files individually

### Additional context

When I select 10 to 20 files or photos share to with anyone it shares a group but I want to share an individual not a grouped 
![image](https://github.com/Nekogram/Nekogram/assets/152393605/fff8d655-aec8-4d5e-b0c4-bc763b6a5a8c)

but I want to share an individual not a grouped 
![image](https://github.com/Nekogram/Nekogram/assets/152393605/bbf466b5-5e52-4cfa-91bf-2a93f369f7b9)

in the video 

1. first select the file 
2. by pressing the middle button mini share window will open 
3. then press and hold the send button to select the option

https://github.com/Nekogram/Nekogram/assets/152393605/b0ca06de-2817-4f04-a4a6-3a749b86973b

this feature is available in [BGram](https://play.google.com/store/apps/details?id=org.telegram.BifToGram) app which is a fork of Telegram but it is a closed source and not update in a long time
https://play.google.com/store/apps/details?id=org.telegram.BifToGram

It is also available on the **telegram desktop** while uploading files or photos
![Screenshot 2024-06-15 141214](https://github.com/Nekogram/Nekogram/assets/152393605/9191220d-5652-4fca-b6a5-b6abc8c1e87d)

Thank you

**Comment by tehcneko** [comment]
sorry, this isn't possible since we are using server-side forward now.

**Comment by Lawless0ne** [comment]
@tehcneko
> sorry, this isn't possible since we are using server-side forward now.

can not you add a button for it 

i am just asking....😭
