### ISSUE TITLE
Multiple account login issues

### ISSUE THREAD

**Issue by c88667220** [Nekogram/Nekogram#104]
### Is your feature request related to a problem?

yes

### Describe the solution you'd like

If you log in to two accounts, only the current account can receive messages, and the other account cannot receive messages. Setting the background resident and background network connection does not work, but the official application can receive messages.

**Comment by tehcneko** [comment]
I can't help with notifications

**Comment by notman1** [comment]
I can't even login into the second account.
It's showing a Connection not initiated error.
