### ISSUE TITLE
[Bug] Rear camera in video messages not working properly

### ISSUE THREAD

**Issue by son1ss** [Nekogram/Nekogram#107]
### Steps to reproduce

1. Turn on rear camera in video messages
2. Start to record video message
3. You see front camera
4. Switch to rear camera and stop
5. Now it starts with rear camera 
6. Restart app
7. Start to record video message
8. See front camera again even though setting is still on

### Expected behaviour

It should just be rear camera always

### Actual behaviour

It starts with front camera after cold start 

### Nekogram version

10.13.1.1

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
#91
