### ISSUE TITLE
[Feature Request] Sliding last seen time

### ISSUE THREAD

**Issue by walterrrossi** [Nekogram/Nekogram#108]
### Is your feature request related to a problem?

No problems, just a suggestion. In same language and I suppose on certain device, that are not so big, it is not possible to see the whole phrase, and so the last seen time is not fully readable. You have to open the profile details to read it correctly. (I'm italian and I use italian interface)

### Describe the solution you'd like

If possible, the last seen time should slide and move, maybe in a cyclic way, in order to show the whole sentence. Another possibilty could be place this sentence in another position, like in another row, to be completely showed.

### Additional context

Device: S23
Version: 10.4.2

**Comment by tehcneko** [comment]
bugs.telegram.org
