### ISSUE TITLE
[Bug] Auto-Night Mode doesn't switch back to day

### ISSUE THREAD

**Issue by CorvetteCole** [Nekogram/Nekogram#11]
### Steps to reproduce

1. Select a day color scheme ("Monet Light")
2. Select a night color scheme ("Monet Dark")
3. Enable "Auto-Night Mode", set to follow "System Default"
4. Enable system dark mode, observe nekogram switches to night theme as expected
5. Disable system dark mode, observe nekogram **DOESN'T** switch to day theme as expected

### Expected behaviour

When "Auto-Night Mode" is set to follow "System Default", the night mode should be activated when the system theme is dark and the day mode should be activated when the system theme is light.

### Actual behaviour

The night mode is activated when the system theme is dark, but is never reset back to the day mode.

### Nekogram version

v10.1.1

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by CorvetteCole** [comment]
For some reason, this isn't always reproducible. I.e. manually switching between the two might work immediately, but long-term it does not. I will try to figure out why

**Comment by tehcneko** [comment]
https://bugs.telegram.org/c/21211

**Comment by CorvetteCole** [comment]
huh, I even poked around a bit. Sorry

**Comment by nexplorer-3e** [comment]
Looks like on latest version (10.2.6,4082) this problem can be reproduced ONLY when **the day theme is custom theme** that are not gram built-in (like Monet Light). 
If use builtin dark theme for day variant the auto switch would not work, as before switch if current theme is dark theme it won't switch. This procedure may be found in Theme.java something like `needSwitchTheme`
Use custom theme for night doesn't affect.
