### ISSUE TITLE
[Feature Request] Streaming Support

### ISSUE THREAD

**Issue by jahidulislamjahid** [Nekogram/Nekogram#125]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Hi there devs love your work, but can we get streaming only (without caching to the device) feature for media files like audio or video? it already exists on another client which is unfortunately desktop only, and there isn't any mobile client with streaming only (without caching the file to the device). So it would be a killer feature for someone like me.

### Additional context

Thanks for all the development till now.

**Comment by tehcneko** [comment]
The desktop client is still saving the file to cache, you can set a size limit or date limit to delete old caches.
