### ISSUE TITLE
[Bug] Push notifications don't work (Google Play)

### ISSUE THREAD

**Issue by KibSquib48** [Nekogram/Nekogram#126]
### Steps to reproduce

1. Receive a message in a chat that isn't muted

### Expected behaviour

I should get a notification while my phone is locked or in another app

### Actual behaviour

I get no notification and I miss the message until I open the app myself

### Nekogram version

11.0.0 (5143) play arm64-v8a

### Android version

15 Beta (AP31.240617.015)

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by NODA5** [comment]
Having the same issue :/

**Comment by tehcneko** [comment]
https://nekogram.app/api-id-migration

**Comment by fuck-lukashenko** [comment]
By any chance, have you faced any issues with push notifications within past few days?

I noticed that recently push notifications stopped working on some (maybe all?) unofficial Telegram android clients. Didn't find any info on that. No push notifications even on older releases of those apps. Examples: P-Telegram, Ime, Telegraph, Nicegram, Vidogram.

Have Telegram changed anything a few days ago / recently? Have you changed anything recently to make notifications work again (except that you mentioned changing api_hash+api_id)?
