### ISSUE TITLE
[Bug] Neko settings to disable stories does not work

### ISSUE THREAD

**Issue by KittehChance** [Nekogram/Nekogram#130]
### Steps to reproduce

Go to Settings
Select Neko Settings
Select General
Enable "Hide Stories"

### Expected behaviour

Stories elements such as the camera icon on chats, and the highlights around user icons in chat should be disabled as they are related to stories.

### Actual behaviour

The camera icon is forced over the chat list taking up space in the interface and accidentally pressing it opens the stories interface, additionally the chat profile icons still highlight when someone posts stories.  I should not be seeing any remnants of the stories interface with stories hidden.

### Nekogram version

11.0.0

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
It's only designed to disable the stories bar
