### ISSUE TITLE
[Bug] notifications are coming late

### ISSUE THREAD

**Issue by vehosah** [Nekogram/Nekogram#131]
### Steps to reproduce

1. Open
2. Get notification
3. The notification comes an hour later than it's supposed to be 

### Expected behaviour

I expected the notification to come when the message came 

### Actual behaviour

The notification came an hour later than the message 

### Nekogram version

11.0.0

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
Telegram's fault

**Comment by scmanjarrez** [comment]
Are notifications delayed on purpose to third party apps? This problem doesn't happen in official telegram client.
