### ISSUE TITLE
[Feature Request] Is it possible to reduce the number of trackers?

### ISSUE THREAD

**Issue by Artem13327** [Nekogram/Nekogram#132]
### Is your feature request related to a problem?

https://reports.exodus-privacy.eu.org/en/reports/tw.nekomimi.nekogram/latest/

### Describe the solution you'd like

Delete all trackers or leave only crash reports

**Comment by tehcneko** [comment]
you can turn it off in settings.

**Comment by Artem13327** [comment]
@tehcneko
Where?

**Comment by tehcneko** [comment]
If you installed from Play Store, you cannot turn if off.

**Comment by Artem13327** [comment]
> If you installed from Play Store, you cannot turn if off.

Maybe in that case you should just give up on any analytics except for crash analytics?

**Comment by tehcneko** [comment]
No.

**Comment by someonehere11** [comment]
> you can turn it off in settings.

I am using the latest GitHub release and I don't see any option to disable analytics either.
The only option I see is "Neko Settings" -> "Other" -> "Send anonymous data".
