### ISSUE TITLE
[Bug] Loosing notifications. mostly all calls get declined. microg last message in august

### ISSUE THREAD

**Issue by gentoosys** [Nekogram/Nekogram#134]
### Steps to reproduce

using nekogram

### Expected behaviour

get instant push notifications

### Actual behaviour

calls get declined even on opened app. 
last message in microg is in august. app is registered in gcm
about text messages they sometimes appear then disappear from notification list
telegram app works fine, I have both

### Nekogram version

11.1.3

### Android version

lineageos 20

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
https://nekogram.app/api-id-migration

**Comment by gentoosys** [comment]
So i just need to log out from telegram and log in back?

**Comment by tehcneko** [comment]
Yes
