### ISSUE TITLE
[Bug]  Can't hide folder tag Icons on neko!

### ISSUE THREAD

**Issue by mablue** [Nekogram/Nekogram#136]
### Steps to reproduce

![IMG_20240927_070857](https://github.com/user-attachments/assets/b739704c-c254-4558-b557-fd2487cf3c0c)

### Expected behaviour

I compared telegram with neko I don't want tag icon on my folder names but I can't hide them.
Because I actually using an emoji for folder names and its also usable as Icon
It's make scrolling very long and not good...

### Actual behaviour

Will not show tags if User used an emoji
Or will have a "disable tag icon" option in chat folders setting

### Nekogram version

11.1.3

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
https://t.me/nekosettings/a?r=tabsTitleType
