### ISSUE TITLE
[Feature Request] Force copy/forward content

### ISSUE THREAD

**Issue by lolion1y** [Nekogram/Nekogram#14]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

add a switch to control forced copy/forward of content  in Neko settings

> If enabled , users can copy/forward msg as usual in groups with the `Restrict saving content` enabled

### Additional context

some groups have enabled `Restrict saving content` ,but in some cases i need to copy/forward some msg

**Comment by tehcneko** [comment]
https://core.telegram.org/api/terms#1-privacy-amp-security
