### ISSUE TITLE
[Bug] Abnormally high CPU usage

### ISSUE THREAD

**Issue by awkwardsmile** [Nekogram/Nekogram#145]
### Steps to reproduce

Disclaimer: I don't know what causes this. 
1. Be inside nekogram or any other TG client.
2. The device continues to heat up and I don't know the cause.

### Expected behaviour

The device should not heat up.

### Actual behaviour

The app occupies a significant amount of CPU usage (constant 100% acc to su top on terminal) and the temps of my device's battery kept climbing till 50 degree celcius when I powered my phone off.

I thought maybe it is downloading something in the background. But the storage section in app is static. Happens even in airplane mode.

This happens on cherrygram, official telegram and ayugram too. 

Neko version: 11.2.3
Official Client: 11.3.3, 11.3.4 (latest as the time of reporting)
Cherrygram: 11.1.3
Ayugram: 10.14.5

### Nekogram version

11.2.3 (Play Store)

### Android version

15

### Reproducible requirement

- [X] I've tested this on official Telegram Android client (11.3.3 and 11.3.4) and this bug is present there too. 

![IMG_20241113_184855_259](https://github.com/user-attachments/assets/ed5a9078-5489-4e74-9061-2698cf2c104e)
![IMG_20241113_184853_239](https://github.com/user-attachments/assets/7961dd5e-a44e-44b7-aa2e-8db7eb9a2cdc)
![IMG_20241113_184858_481](https://github.com/user-attachments/assets/3d406125-c02e-4460-bef9-e4c0d241fb37)
![IMG_20241113_184857_646](https://github.com/user-attachments/assets/c26516c8-93c6-4eb4-85b6-e1b316208e76)

Logs:
[Ayugram.zip](https://github.com/user-attachments/files/17733070/Ayugram.zip)
[Cherrygram.zip](https://github.com/user-attachments/files/17733072/Cherrygram.zip)
[Nekogram.zip](https://github.com/user-attachments/files/17733075/Nekogram.zip)
[OfficialTelegram.zip](https://github.com/user-attachments/files/17733077/OfficialTelegram.zip)

**Comment by tehcneko** [comment]
> This happens on cherrygram, official telegram and ayugram too.
