### ISSUE TITLE
[Bug] Main camera (aka story camera)

### ISSUE THREAD

**Issue by EduardoRGCM** [Nekogram/Nekogram#149]
### Steps to reproduce

1. Open app
2. Click on camera icon on home screen
3. Camera stucked

### Expected behaviour

Camera should be working fine

### Actual behaviour

Camera froze, video and photo

### Nekogram version

11.4.2

### Android version

15

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by EduardoRGCM** [comment]
Note: if i hide/disable the double camera button (Debug Settings), works fine

**Comment by tehcneko** [comment]
bugs.telegram.org
