### ISSUE TITLE
[Bug] The application does not open 

### ISSUE THREAD

**Issue by blonixie** [Nekogram/Nekogram#152]
### Steps to reproduce

1. Login to the application 
2. After a few seconds the app crashes 
3. Repeat the first two steps each time

### Expected behaviour

To avoid these crashes 

### Actual behaviour

Hello. I came across a bug when the application does not open. I tried several ways to solve it somehow. Unsuccessfully. Now I ask for your help! 

Crash file: 
[crash-tw-nekomimi-nekogram-10_12-22-57-31_752.zip](https://github.com/user-attachments/files/18087485/crash-tw-nekomimi-nekogram-10_12-22-57-31_752.zip)
And what does it look like: 
https://github.com/user-attachments/assets/61d450e3-7ff9-47f9-91db-6adbf7018317

### Nekogram version

11.5.3

### Android version

SM-A135F/DSN armeabi-v7a

### Reproducible requirement

- [x] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by MacyBaston** [comment]
it's crashes for me too

**Comment by tehcneko** [comment]
it's out of memory error, Telegram doesn't work well on low spec devices anymore :(
