### ISSUE TITLE
[Bug] Client crashes shortly after being opened.

### ISSUE THREAD

**Issue by ghost** [Nekogram/Nekogram#153]
### Steps to reproduce

[Error in Nekogram c449a68ddb91.txt](https://github.com/user-attachments/files/18136714/Error.in.Nekogram.c449a68ddb91.txt)

I attached the crash report in a .txt file below. I've never had this sort of issue with Nekogram before, it only started happening after the latest update. Can I fix this on my own? Or will this require an entirely new update? 

### Expected behaviour

The client should function normally.

### Actual behaviour

The client crashes after around 10 seconds.

### Nekogram version

v11.5.3 (latest)

### Android version

15

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
it's out of memory error, Telegram doesn't work well on low spec devices anymore :(

**Comment by ghost** [comment]
> it's out of memory error, Telegram doesn't work well on low spec devices anymore :(

The regular Telegram client functions normally, I'm only having issues with Nekogram so it can't be true that TG doesn't work well on "low spec devices" anymore. 

As for the "low spec device" I'm using: it's a phone that was introduced just last year. It can't possibly be that bad. 

I don't think this ticket should've been closed so early.
