### ISSUE TITLE
[Bug] crash after log in

### ISSUE THREAD

**Issue by W1neus** [Nekogram/Nekogram#155]
### Steps to reproduce

Install 11.5.3
Log in to account
My phone: xiaomi redmi note 10s
Os: miui 13.0.16

https://github.com/user-attachments/assets/297addf4-3bad-4f85-ac7b-172631e30040

### Expected behaviour

App will not crash 

### Actual behaviour

App will crash 

### Nekogram version

11.5.3

### Android version

12

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by W1neus** [comment]
Os crash log
![Screenshot_2024-12-18-11-39-08-024-edit_com miui bugreport](https://github.com/user-attachments/assets/6f811a8a-4cba-4c08-86ec-9da208900c68)

**Comment by blonixie** [comment]
i have exactly the same problem, but the devs decided not to solve this problem :/
