### ISSUE TITLE
[Bug] Android 14 full access storage need

### ISSUE THREAD

**Issue by RooGhz720** [Nekogram/Nekogram#157]
### Steps to reproduce

when I access or send files in the form of archives from within the application directly on the android 14 aosp that I use, it doesn't work

"you do not have an application that can open the 'application/zip' file, please install one to continue"
![Screenshot_20241223-061415](https://github.com/user-attachments/assets/a801f4b5-d219-4dfb-b522-5f86c3eb2cea)

### Expected behaviour

pls add permission "MANAGE_EXTERNAL_STORAGE"

### Actual behaviour

on official telegram app is sams not support full storage access android 14

### Nekogram version

11.5.3 (55111)

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
your rom issue

**Comment by RooGhz720** [comment]
> your rom issue

but, on another rom a14 aosp this issue is same, and some people don't care, and choose to save it first and then open it via file manager

**Comment by tehcneko** [comment]
try formating data with another rec
