### ISSUE TITLE
[Feature Request] Filter polls in group info

### ISSUE THREAD

**Issue by angeousta** [Nekogram/Nekogram#18]
### Is your feature request related to a problem?

When you look at a group info, you can browse only files, links, media, voice, music, gif. I'd like to add "polls" to that

### Describe the solution you'd like

See above

**Comment by tehcneko** [comment]
This requires Telegram API to do.

**Comment by angeousta** [comment]
Even if the server won't let you, you can create a local db where you store poll message id, in a table like polls (chat_id, message_id) when you receive each message if it's a poll you populate that db so you can make the list, so the index is local and not remote
