### ISSUE TITLE
[Bug] 频道图片加载问题

### ISSUE THREAD

**Issue by clevercjl** [Nekogram/Nekogram#22]
### Steps to reproduce

1.打开有图片的频道
2.上滑几下后图片不加载
官方客户端没有此问题

### Expected behaviour

图片正常加载

### Actual behaviour

图片不加载
![Screenshot_20231022_132945](https://github.com/Nekogram/Nekogram/assets/81756592/e523d4ba-7609-4476-a6c5-c0b7cf348892)

### Nekogram version

10.1.1.1

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
不能复现，你用的内置代理吗？

**Comment by clevercjl** [comment]
不是，用的机场，我的网络肯定没问题，推特油管都正常

**Comment by clevercjl** [comment]
讨论群里也有另一位用户遇到同样的问题
![Screenshot_20231028_145711](https://github.com/Nekogram/Nekogram/assets/81756592/c8ced2fa-0c1b-4399-b041-187b1881da21)

https://github.com/Nekogram/Nekogram/assets/81756592/db1bc1a0-3d63-4db1-808c-1ffd267b3bcc

**Comment by clevercjl** [comment]
图片和视频里频道的链接 https://t.me/YunRan1314  https://t.me/pixiv_top50
试试这两个频道，往上滚动一会儿图片就不加载了，原版客户端是正常的

**Comment by clevercjl** [comment]
看一下回复

**Comment by clevercjl** [comment]
看一下回复

**Comment by clevercjl** [comment]
看下回复

**Comment by clevercjl** [comment]
看下回复

**Comment by calpa2007** [comment]
1

**Comment by clevercjl** [comment]
看下回复

**Comment by clevercjl** [comment]
看下回复
