### ISSUE TITLE
[Feature Request] If API makes it possible, a real live map showing geogroups on that

### ISSUE THREAD

**Issue by ArmeF97** [Nekogram/Nekogram#22]
A simple map showing geogroups all around the world.
Is it too much? I don't know if API supports this

**Comment by NekoInverter** [comment]
Impossible

**Comment by rikakomoe** [comment]
Hello! I'd like to explain deeper into this question. Telegram has only an API that gives you geogroups nearby. A single map all over the world will need a lot of single requests. Not to mention the huge data flow and slow user experience, the API has a rate limit which doesn't allow us to do so.

**Comment by RememberTheAir** [comment]
@rikakomoe maybe @ArmeF97 was suggesting to show in a map only the chats the API returns from a single request

**Comment by ArmeF97** [comment]
No, I was suggesting a global thing. 
As I now learn, thanks to @rikakomoe (and @RememberTheAir suggestion), my feature request could be transformed in a new one, taken what I learned in mind. If anyone wants to open a more possible feature request, feel free to do so. 

I'll think of something in the future (in this moment I'm busy sorry)

**Comment by RememberTheAir** [comment]
I honestly don't care about such a feature but if the dev want to go about it, Telegram offers a similar view when you share a live location with many people. I guess part of that code can be reused into this new feature, replacing users with chats, if it ever gets worked on
