### ISSUE TITLE
Some suggestions for new features

### ISSUE THREAD

**Issue by HitaloKun** [Nekogram/Nekogram#23]
# Some suggestions

- [x] 1. Add an option to turn off the "repeat" button.
- [ ] 2. Make Nekogram tabs more intuitive, make them appear only by holding the top of the screen, as it is on Telegram X.
- [x] 3. Add the streaming functions of MKV videos and all videos.

**Comment by rikakomoe** [comment]
1. No
2. No
3. Contribution welcomed
