### ISSUE TITLE
@通知问题

### ISSUE THREAD

**Issue by Forty-nine** [Nekogram/Nekogram#3]
我把某一个群禁止通知后，该群@我的消息，没有声音与震动，只会有通知，请教如何解决（千万别告诉我，我要一个一个群设置，哭唧唧

**Comment by NekoInverter** [comment]
上游问题

**Comment by rikakomoe** [comment]
@Forty-nine 我觉得这是你设置或者是系统设置的问题，因为我测试了并没有这个问题，静音的群被 @ 的时候是会有声音和震动的
