### ISSUE TITLE
[Feature Request] F-Droid support

### ISSUE THREAD

**Issue by angeousta** [Nekogram/Nekogram#30]
### Is your feature request related to a problem?

Add this app to f-droid store

### Describe the solution you'd like

See above

**Comment by marek22k** [comment]
@tehcneko Why did you close the issue?

**Comment by angeousta** [comment]
> @tehcneko Why did you close the issue?

Because it was marked as "not planned", meaning he/she doesn't want to do it, it's as simple as that

**Comment by bt4ibwem8** [comment]
What is the reason for this decision?

**Comment by tehcneko** [comment]
you can do it if you want to.
