### ISSUE TITLE
[Bug] autoplay of video messages from blocked group users

### ISSUE THREAD

**Issue by alhimiker** [Nekogram/Nekogram#33]
### Steps to reproduce

The bug concerns the "Hide messages from blocked user" option.
Condition for reproducing the bug:
1. You have the "Hide messages from blocked user" option enabled.
2. You are a member of a tg group of many users. You blocked one of them.
3. Participants who are not blocked by you record video messages (in circles =) sorry, I don’t know what they call it in the English-speaking environment).
4. Then the user you blocked does the same.
5. Then you go to the group to view new messages.
6. You start viewing a video message from a non-blocked user.
7. Then all subsequent video messages begin to play one after another until the turn of a message from the blocked user arrives.
8. This video message, like the others, appears on your screen with sound, in the order of the general queue.

I believe the same thing will happen with voice messages.

### Expected behaviour

The expected result is that you do not see any messages from the blocked user until you deliberately reveal the spoiler.

### Actual behaviour

You accidentally see a video message from a blocked user. No spoiler reveal.

### Nekogram version

10.2.6 (4082) arm64-v8a

### Android version

14 UP1A.230620.001    MIUI 14.0.7.0

### Reproducible requirement

- [x] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
fixed in 10.2.9
