### ISSUE TITLE
[Bug] Crashed on armeabi-v7a Devices

### ISSUE THREAD

**Issue by BLxcwg666** [Nekogram/Nekogram#34]
### Steps to reproduce

1. Open [Telegram Channel](https://t.me/NekogramAPKs)  
2. Download `Nekogram-10.2.9-4087-armeabi-v7a.apk`  
3. Install Apk
4. Open Nekogram
5. Wait for 5-6 seconds
6. Nekogram Crashed  
  
I tried to install `Nekogram-9.6.5-3357-armeabi-v7a.apk` and found that this version can be used normally, but overwriting this version and installing the 10.2.9 version can be opened and used, but it still crashes after waiting for 5-6 seconds. Last week I uninstalled the 10.2.6 version that I was using normally for some reasons. This week when I tried to install the 10.2.6 version again I found this crash problem.

### Expected behaviour

Nekogram runs normally

### Actual behaviour

Nekogram crashed

### Nekogram version

10.2.9

### Android version

5.1.1 (Lollipop)

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
Please attach crash logs.

**Comment by BLxcwg666** [comment]
Sorry, I don't know much about Android. I captured the LogCat of the process when I opened nekogram and waited for it to crash. I hope it helps. If this is wrong, how can I get the crash log?
[log_2023-11-18-14_12_03.txt](https://github.com/Nekogram/Nekogram/files/13399206/log_2023-11-18-14_12_03.txt)

**Comment by tehcneko** [comment]
日志没看出来什么问题，不知到是不是你什么模块弄坏的
