### ISSUE TITLE
Request for f-droid tracker-free version.

### ISSUE THREAD

**Issue by b3pio** [Nekogram/Nekogram#34]
Please consider a F-droid or github only version with the Google and Microsoft trackers removed. ACRA is a viable privacy respecting tracker if you really need to track anything within the app. Google and microsoft violate user privacy which goes against the values of Telegram. Please just don't delete this request.

**Comment by SonicoXD1** [comment]
This would require Nekogram to be worked on Telegram-FOSS, right? 
I agree it would greatly help with privacy, but at the same time it would be annoying for the dev to mantain two separate versions of the app. I may be wrong though.

**Comment by b3pio** [comment]
If it was altered to be suitable for f-droid, this same version can be submitted to play store also. So only one version would be required.

> This would require Nekogram to be worked on Telegram-FOSS, right?
> I agree it would greatly help with privacy, but at the same time it would be annoying for the dev to mantain two separate versions of the app. I may be wrong though.

**Comment by SonicoXD1** [comment]
> If it was altered to be suitable for f-droid, this same version can be submitted to play store also. So only one version would be required.
> 
While true, doing so means disabling Google's push notifications. As seen in Telegram-FOSS, that means an increase in battery consumption if you want to get reliable notifications. So, many users will be affected negatively by this change.

**Comment by NekoInverter** [comment]
https://github.com/Nekogram/Nekogram-FOSS/

**Comment by federa7675** [comment]
Is there any chance we get nekogram in f-droid? nekogram-foss seems out of date compared to the regular nekogram

Here is the conversion about it in F-droid repo:
https://gitlab.com/fdroid/rfp/-/issues/1241#note_331452707

Thanks for your efforts 👏️👏️👏️
