### ISSUE TITLE
[request] quick share sheet as the default when forwarding a message

### ISSUE THREAD

**Issue by RememberTheAir** [Nekogram/Nekogram#40]
**Is your feature request related to a problem? Please describe.**

I've been using Telegram X for the past year and one design choice I think it nailed is to always use the quick share menu when forwarding something. Why I think it's much better than picking the chat from the classic chats list:

- it shows much many chats as soon as you open it, without having to scroll. It's easier to find a chat in a glance
- the chats are easier to reach. You don't have to stretch your thumb to reach the top of your screen
- the search icon is much easier to reach, for the same reason
- you can quickly add a comment to the medias you share
- you can easily select multiple chats and it is easier to see which chats you have selected
- it's harder to read your chats' names for people around you when you are in public places

It would be nice to have an option to always use it or make it the default sharing view when forwarding a message

**Describe the solution you'd like**

Have the forward icon default to the quickshare sheet

**Describe alternatives you've considered**

None

***

I know this is a duplicate of #33, but it has been closed by OP for unknown reasons

**Comment by SonicoXD1** [comment]
+1 for this.

**Comment by alsoGAMER** [comment]
Use TGX, it's easy huh?
Braindead monkey

**Comment by 2ciyv** [comment]
Yes, I also need this function very much.
