### ISSUE TITLE
[request] option to start video message recording with the rear camera

### ISSUE THREAD

**Issue by RememberTheAir** [Nekogram/Nekogram#41]
**Is your feature request related to a problem? Please describe.**
I would like to start recording video messages with the rear camera way more often than with the front one

**Describe the solution you'd like**
An option under nekosettings to make the read camera as the default recording camera for video messages

**Describe alternatives you've considered**
None

**Comment by alsoGAMER** [comment]
Use TGX, it's easy huh?
U're also an admin!
[Braindead monkey](https://github.com/Nekogram/Nekogram/issues/61#issuecomment-606135066)

**Comment by RememberTheAir** [comment]
Implemented in 6.0.1.3
