### ISSUE TITLE
Force close when I see the Telegram Premium feature

### ISSUE THREAD

**Issue by fugoou** [Nekogram/Nekogram#41]
### Steps to reproduce

https://github.com/Nekogram/Nekogram/assets/89079801/6d5ad554-8b67-4af6-8292-6bfb4a016809

### Expected behaviour

-

### Actual behaviour

-

### Nekogram version

10.3.2

### Android version

11

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
this will be resolved in future version.
