### ISSUE TITLE
[Request] some shortcuts to group administration

### ISSUE THREAD

**Issue by HitaloKun** [Nekogram/Nekogram#42]
Could you add these shortcuts to Nekogram? (Telegraph screenshots)

![](https://i.imgur.com/bskPl3l.jpg)

![](https://i.imgur.com/VAVkWaj.jpg)

**Comment by SonicoXD1** [comment]
I think this would just unnecessarily bloat the interface. To get to where you want, only one extra tap is needed on the pencil button.
