### ISSUE TITLE
[FR] unread chats first

### ISSUE THREAD

**Issue by bestpika** [Nekogram/Nekogram#45]
Could you add an option is unread chats sort first?

**Comment by SonicoXD1** [comment]
Isn't that the default behavior?...

**Comment by bestpika** [comment]
@SonicoXD1 The default behavior is sorted by send time.

**Comment by SonicoXD1** [comment]
I get what you mean now, sorry. 
It'd be a great feature, but isn't chat filtering good enough? It displays unread badges for all unlisted chats under a same category.

**Comment by bestpika** [comment]
Someone will miss the unread chat if he has a lot of chats.

**Comment by alsoGAMER** [comment]
It might make sense if implemented as a filter on the tabs (the original ones of nekogram)

**Comment by NekoInverter** [comment]
I think unread folder is enough.
