### ISSUE TITLE
[BUG] upload multiple files fails

### ISSUE THREAD

**Issue by X-Oracle** [Nekogram/Nekogram#45]
### Steps to reproduce

1. Go to any file explorer
2. Select multiple files
3. Share them to nekogram
4. Select desired chat (ex: saved messages)

### Expected behaviour

It should have uploaded them one by one.

### Actual behaviour

You will see it will show failed for all of them

### Nekogram version

10.3.2

### Android version

12 ( Xiaomi miui 13)

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
it fails on official too
