### ISSUE TITLE
[question] save to private directory: where are cached files saved?

### ISSUE THREAD

**Issue by RememberTheAir** [Nekogram/Nekogram#47]
Hello there,

when the "save cache to private directory" option is enabled, where are cached files saved? I assume they are under `/data/data/tw.nekomimi.nekogram/`, but I'm not entirely sure about that. If so, I assume that the "clear medias" option in the storage settings won't work when the option is enabled and the only way to clean this private storage is to delete the app's data, right?

Edit: from [the commit](https://github.com/Nekogram/Nekogram/commit/829026840a7218ffd0216110431e767f67d674f6) that brings this option, it looks like that when the option is enabled, `getFilesDir` is used rather than `Environment.getExternalStorageDirectory` to get the path where to save cached medias, ~and as far as I can read on Android's docs, `getFilesDir` returns the app's internal directory which can't be accessed without root access. If that's correct & settled, the main question is how to clean the cache when the option is enabled?~ wrong, see edit 2

Edit 2: so, I did some tests. Apparently files are not saved in `/data/data/tw.nekomimi.nekogram/cache/sdcard` as i thought. It appears they're still in my ~internal~ external storage under the `./Telegram` directory, but I cannot see them from a file manager. I tested by cleaning my cached media and then downloading a ~500 mb video from Nekogram. Now if I open `Telegram/Telegram Videos` using MiX file manager, I only see the `.nomedia` file but the directory is reported to be ~500 mb large. Also, from nekogram's storage settings, I see that the app has ~500 mb of videos saved, so i can clean them from there. Interesting. This also explains why `File()` is called with "Telegram" as second argument, because that's the directory. So `File(ApplicationLoader.applicationContext.getFilesDir(), "Telegram")` returns a File object that is still in the external storage, but only accessible by the app? So, as opposed to how normal Telegram works, files saved by Nekogram when this option is enabled are not accessible by apps with the `READ_EXTERNAL_STORAGE` permission?

**Comment by HitaloKun** [comment]
@RememberTheAir That's a good question, I wanted to know the answer, too.

**Comment by telegramcore** [comment]
I don't see any private folder, too, the media are sent normally in /storage/emulated/0/Telegram

Probably it's a bug (?)

**Comment by RememberTheAir** [comment]
> I don't see any private folder, too, the media are sent normally in /storage/emulated/0/Telegram

> Probably it's a bug (?)

The medias are cached there, but you can't access them from other apps, hence "private". I guess it works correctly. I was just curious about how this is handled but I guess I almost figured out. It's just weird that `applicationContext.getFilesDir()` returns a path pointing to the external storage but maybe I'm misundertanding how this API is supposed to work

**Comment by NekoInverter** [comment]
"Telegram" folder is saved to /data/data/tw.nekomimi.nekogram/files/Telegram

**Comment by RememberTheAir** [comment]
Oh, right. I didn't notice that directory. Now everything makes sense. Turns also out that the size of `/storage/emulated/0/Telegram/Telegram Video` shown by MiX was an unfortunate caching issue. Thanks!
