### ISSUE TITLE
[Bug] Sharing selected text from messages shares NULL value

### ISSUE THREAD

**Issue by FrosT2k5** [Nekogram/Nekogram#48]
### Steps to reproduce

1. Select any text from a chat message
2. Click the 3 dots -> Share button
3. Select an app to share (like Read Aloud) 

### Expected behaviour

Should share the selected text as string, attached a video which shows NULL value is passed. 

https://github.com/Nekogram/Nekogram/assets/62540315/ed83a7db-df2f-49b3-ac8d-ebb61b111071

### Actual behaviour

A NULL value is passed instead of actual text

### Nekogram version

10.3.2

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
This will be fixed in next release.
