### ISSUE TITLE
Blocked user's messages in group chat are still displayed

### ISSUE THREAD

**Issue by kumikooumae** [Nekogram/Nekogram#49]
**Describe the bug**
Blocked user's messages in group chat are still displayed, after ignore blocked users in group is enabled.

**To Reproduce**
1. Exit the app and relaunch 
2. Enter a group chat
3. Blocked user's messages are still displayed
4. a) Enter Settings -> Privacy and Security -> Blocked users, or b) click the blocked user's avatar
5. Return to the group chat
6. Blocked user's messages are hidden

**Expected behavior**
Blocked user's messages are hidden everytime the app is launched, if ignore blocked users in group is enabled.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: MI6
 - OS: Android8.1
 - Version 5.15.0.3

**Additional context**

**Comment by NekoInverter** [comment]
Known issue

**Comment by kumikooumae** [comment]
Wiping data may help 🤔
