### ISSUE TITLE
[Bug] 保存图片时没有弹窗提示“已成功保存至相册”

### ISSUE THREAD

**Issue by lndslyn** [Nekogram/Nekogram#5]
### Steps to reproduce

1.点击任一张图片
2.点击右上角
3.点击保存至相册

### Expected behaviour

弹窗提示“已成功保存至相册”

### Actual behaviour

无弹窗，但是能成功保存

### Nekogram version

10.0.9(3867)arm64-v8a

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
This issue exists on the official Telegram, please report it to https://bugs.telegram.org
