### ISSUE TITLE
[request] add a shortcut to paste links

### ISSUE THREAD

**Issue by HitaloSama** [Nekogram/Nekogram#50]
It would be very useful and practical a shortcut to paste links, just a "paste" button in this box would be great.

![](https://i.imgur.com/UhEVZq3.jpg)

**Comment by NekoInverter** [comment]
Why not long press to paste

**Comment by HitaloKun** [comment]
@NekoInverter the long press is considere slow on some devices so a shortcut would be much faster and more practical.

**Comment by SonicoXD1** [comment]
> @NekoInverter the long press is considere slow on some devices so a shortcut would be much faster and more practical.

You could also use another keyboard. Fleksy allows you to have a paste button on the top row.
