### ISSUE TITLE
[BUG] "Forward with quote" option doesn't work in action bar

### ISSUE THREAD

**Issue by groozchique** [Nekogram/Nekogram#51]
**Describe the bug**
When you select the message and try to forward it with the quote by tapping on icon in a action bar, it forwards it without quote. So basically we have two options doing the same thing.

**To Reproduce**
1. Select the message by long-tap
2. Tap on "Forward with quote" icon on action-bar
3. Forward the message
4. Message will be forwarded without a quote

**Expected behavior**
"Forward with quote" should remain quote if forwarded

**Smartphone (please complete the following information):**
 - Device: Xiaomeme Poco F1
 - OS: Android 10
 - Version: 5.15.0.3

**Comment by NekoInverter** [comment]
I can't reproduce, could you provide more information?

**Comment by groozchique** [comment]
Sure, here's a video: https://gfycat.com/differentweeklyaphid

**Comment by NekoInverter** [comment]
![image](https://user-images.githubusercontent.com/42698724/75602975-3c214980-5b05-11ea-8e2c-87bab6b7ad2b.png)
![image](https://user-images.githubusercontent.com/42698724/75602981-46dbde80-5b05-11ea-91e6-473595712d35.png)
What's the problem?
What you pressed first is **Forward without quote**

**Comment by groozchique** [comment]
Yeah, my bad :P

I guess I'm used to stock client button placement, so I pressed this out the habit.

Sorry for any inconveniences.

**Comment by groozchique** [comment]
If those buttons placement could be swapped (so they will have same order as in "Message menu"), it would be nice
