### ISSUE TITLE
[Request] Enhancement for inbox contents 

### ISSUE THREAD

**Issue by ArchiveBase** [Nekogram/Nekogram#52]
Could you split inbox contents into two or three categories as showed on below screenshot?
- Display the counter (eg: if a contact or a group received messages then count as one not total messages per contact)
- Keep the existing 'search' icon. Input field able to expand if user tap on the icon.

![Untitled](https://user-images.githubusercontent.com/46082456/75613299-8e428900-5b5e-11ea-98b6-090d907d77fe.png)

Why this feature? we have many groups, contacts(individual), channels then sometimes we see individuals messages after many days because often get covered by groups.
_(I do not want to request this feature from official telegram because afraid that may copy by other madness messaging services)_

**Comment by HitaloKun** [comment]
You could just follow the style of Telegram X, two tabs, one of another call-up conversations and holding already conversations would open the categories.

**Comment by SonicoXD1** [comment]
Almost the same is already available. 
![Screenshot_20200229-170211_Nekogram~2](https://user-images.githubusercontent.com/61394886/75614232-7abf0000-5b15-11ea-809e-5c365dc5d443.jpg) ![Screenshot_20200229-170216_Nekogram](https://user-images.githubusercontent.com/61394886/75614237-84e0fe80-5b15-11ea-8da3-20627e967a12.jpg)

**Comment by HitaloKun** [comment]
@SonicoXD1 yes but it should be in the same style as Telegram X, it would be much more intuitive and beautiful.

**Comment by ArchiveBase** [comment]
- Display above mentioned 3 categories(filters) on the top by default as showed on screenshot
- User able to view rest of categories(6) using the way as already has.

**Comment by NekoInverter** [comment]
No tabs

**Comment by ArchiveBase** [comment]
Well, atleast i knew nekogram has such feature after @SonicoXD1 showed it

**Comment by SonicoXD1** [comment]
> @SonicoXD1 yes but it should be in the same style as Telegram X, it would be much more intuitive and beautiful.

If it were intuitive, then there wouldn't be a lot of people on the Telegram X chat asking how to show filters. It isn't intuitive, and the way it is right now doesn't clutter the app in any way. You also get to learn about it by just checking neko settings.
Sorry for writing after the issue was closed.

**Comment by ArchiveBase** [comment]
@NekoInverter ;)
https://telegram.org/blog/folders
