### ISSUE TITLE
Photos and Videos sent in Secret Chat are always broken[Bug] 

### ISSUE THREAD

**Issue by indicaxfa123** [Nekogram/Nekogram#53]
### Steps to reproduce

1. Get into secret chat with someone using normal telegram.
2. Sent a photo or video from nekogram secret chat to other guy using normal telegram
3. The other guy with normal telegram gets the image/video crashed or unreadable form.

### Expected behaviour

The guy with normal telegram should be able to view and see the image or video sent from nekogram secret chat without any issue

### Actual behaviour

The other guy with normal telegram gets the image/video crashed or unreadable form.

### Nekogram version

10.5.0

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
This is caused by a bug in official Telegram Android, you can turn Send Large Photo off in Experimental settings.
