### ISSUE TITLE
[BUG] Bold system font stopped working since v1875

### ISSUE THREAD

**Issue by SonicoXD1** [Nekogram/Nekogram#54]
**Describe the bug**
If system font is enabled, it won't be bold in places where it should be, like the app's titlebar. 

**To Reproduce**
1. Go to Neko Settings. 
2. Click on Use system default font. 
3. Restart the app. 
4. The font will be the same across the whole app, instead of there being a difference between bold and regular. 

**Screenshots**
![Screenshot_20200301-131850_Nekogram](https://user-images.githubusercontent.com/61394886/75629324-c928d900-5bbf-11ea-9c3f-ce42558d244f.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge
 - OS: Android 9.0
 - Nekogram 5.15.0.3 (1875)

**Additional context**
My system font is Google Sans, and it includes Bold, Medium, Italic and Regular. I did however try with other fonts too, with the same result.

**Comment by NekoInverter** [comment]
Your fonts are not configured properly

**Comment by SonicoXD1** [comment]
> Your fonts are not configured properly

May I ask what that means? It was working fine before the update.

**Comment by NekoInverter** [comment]
> > Your fonts are not configured properly
> 
> May I ask what that means? It was working fine before the update.

You don't have medium and Nekogram is using medium.
