### ISSUE TITLE
[Bug] Group video chat behavior and force close of Nekogram

### ISSUE THREAD

**Issue by white-miku** [Nekogram/Nekogram#55]
### Steps to reproduce

1. Start group video chat
2. Go to home screen
3. Disable notification
4. Return to Nekogram and try to toggle microphone (mute/unmute)

### Expected behaviour

Nekogram continues working

### Actual behaviour

"Nekogram has stopped"

### Nekogram version

10.5.0

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by white-miku** [comment]
Let me explain this bug report.
When I'm starting a group video chat on latest Telegram, a "standard" notification appears in statusbar.
![Screenshot_20240115-135742_Nova Launcher](https://github.com/Nekogram/Nekogram/assets/30299222/2a925012-b134-4ecd-8ed3-614bcfe5fb62)
![Screenshot_20240115-135745_Nova Launcher](https://github.com/Nekogram/Nekogram/assets/30299222/14da1ac0-2cf5-44ac-ae0c-c3c067899c7f)
But when I'm starting a group video chat in Nekogram, an "active call" notification appears in statusbar.
![Screenshot_20240115-135813_Nova Launcher](https://github.com/Nekogram/Nekogram/assets/30299222/3ca943d1-1c00-42dd-9212-01480b7f8dce)
![Screenshot_20240115-135819_Nova Launcher](https://github.com/Nekogram/Nekogram/assets/30299222/965bb75f-8d7b-473c-a055-81c0142b65b6)
The pill with a timer preventing statusbar from being hidden in fullscreen games for example. And when I'm trying to disable it and then toggle the microphone on or off, Nekogram forcefully closes.
![Screenshot_20240115-135829_Nova Launcher](https://github.com/Nekogram/Nekogram/assets/30299222/647e7027-5879-4bbd-b731-17ace9a86d16)
![Screenshot_20240115-135844_Nova Launcher](https://github.com/Nekogram/Nekogram/assets/30299222/dab3fcd8-65a0-454c-9d85-a0408d33c001)

**Comment by tehcneko** [comment]
The same crash happened to me on the official client from your steps.

**Comment by white-miku** [comment]
@tehcneko I agree, but official Telegram client doesn't require to disable this notification because it doesn't adding the "pill" in statusbar with timer while in group video chat which Nekogram does.
