### ISSUE TITLE
[Question] Why all the proxy settings?

### ISSUE THREAD

**Issue by zSucrilhos** [Nekogram/Nekogram#57]
Hello, i installed the app and it works like a charm, it is really very good, the problem that i don't see why apply proxys to the client, and why do this? Also, i haven't found anything not in the app itself, nor in the PlayStore description, nor in the README on this repository. I would like to know. The app is very good, but all these proxys made me smell a rat on this app... I did not do any network analysis on the app's traffic bc i thought i'd as here first. Thanks.

**Comment by NekoInverter** [comment]
What proxy?
There isn't any proxy built-in.
