### ISSUE TITLE
[request] Bring back the old tabs

### ISSUE THREAD

**Issue by alsoGAMER** [Nekogram/Nekogram#61]
**Is your feature request related to a problem? Please describe.**
The tabs implemented from the latest telegram update really sucks on mobile devices

**Describe the solution you'd like**
Bring back the old tabs, those that were before the update to version 6.0, and improve that feature

**Comment by LucaTheHacker** [comment]
+1

**Comment by Gi4cca** [comment]
+1

**Comment by damettoluca** [comment]
+1

**Comment by florin88** [comment]
+1

**Comment by RememberTheAir** [comment]
Reactions are a thing

**Comment by alsoGAMER** [comment]
> Reactions are a thing

and so?

**Comment by RememberTheAir** [comment]
@alsoGAMER you can stop to act like braindead monkeys and start using the tools how they're meant to be used

**Comment by LucaTheHacker** [comment]
> @alsoGAMER you can stop to act like braindead monkeys and start using the tools how they're meant to be used

also your name should remember it to you

**Comment by alsoGAMER** [comment]
@RememberTheAir Ok so since you said it, I don't have to post any tips anymore on github.
Stop it, you're just making yourself ridiculous.

**Comment by HitaloSama** [comment]
There is no need for that, you can use Telegram folders as tabs, just don't be lazy and set them up.

**Comment by alsoGAMER** [comment]
> There is no need for that, you can use Telegram folders as tabs, just don't be lazy and set them up.

I know there are telegram folders (in fact on desktop I use them), but they are inconvenient to use on mobile, the original nekogram tabs, instead they were much more practical, just make them more accessible

**Comment by NekoInverter** [comment]
@alsoGAMER Don't spam issues or you will get banned

**Comment by SonicoXD1** [comment]
> > There is no need for that, you can use Telegram folders as tabs, just don't be lazy and set them up.
> 
> I know there are telegram folders (in fact on desktop I use them), but they are inconvenient to use on mobile, the original nekogram tabs, instead they were much more practical, just make them more accessible

Let's rewrite what you actually (should) want.
Use Telegram's folders the same way Nekogram used filters before (by tapping on the pencil icon or on the top bar). That is:
1. Set up folders as you want inside Telegram settings.
2. Folders don't show as tabs (as in the main client). Instead, they only show when either tapping on the pencil icon or on the top bar.
That would make more sense. But disabling stock folders completely, and going back to simply "filters" (groups, channels, etc.) doesn't.

**Comment by KlausDevWalker** [comment]
> > There is no need for that, you can use Telegram folders as tabs, just don't be lazy and set them up.
> 
> I know there are telegram folders (in fact on desktop I use them), but they are inconvenient to use on mobile, the original nekogram tabs, instead they were much more practical, just make them more accessible

I think what you're trying to say by "incovenient" is that they could use icons instead of the word labels. If that is the case, I agree with you. But let's the dev decide if it's practical to change on this Telegram's new source code :)
