### ISSUE TITLE
[Bug] push doesn't work (without GSF)

### ISSUE THREAD

**Issue by reinold-p** [Nekogram/Nekogram#64]
### Steps to reproduce

I set all the 3 settings to get notifications on
I set in system settings battery usage not optimized

### Expected behaviour

I exspect notifications at least when phone isn't in deep sleep

### Actual behaviour

I've to open the app to see new posts

### Nekogram version

10.6.4

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
working as expected, you need gms for notification to work

**Comment by KweezyCode** [comment]
is there any way to get notifications without gms?
