### ISSUE TITLE
[request] mute separated account

### ISSUE THREAD

**Issue by SuperCz1** [Nekogram/Nekogram#64]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Since Nekogram has multi-account support, it would be great if we can choose which account can send notifications, without disabling every single switch in the settings.
Maybe you could add an option under Nekosettings that allows you to choose which account can send notifications.

**Comment by RememberTheAir** [comment]
As a workaround, there's a Telegram setting that allow you to receive notifications only from the active account. Anyway, Telegram should really fix his notifications channels management because using Android's notifications settings would be much easier
