### ISSUE TITLE
[Bug] Strange options appear in the long press menu

### ISSUE THREAD

**Issue by fxzxmicah** [Nekogram/Nekogram#67]
### Steps to reproduce

Long press the desktop icon.

### Expected behaviour

I don't know what to expect.

### Actual behaviour

![Screenshot_20240221_224503](https://github.com/Nekogram/Nekogram/assets/48860358/50bafaf1-0e12-4763-bb19-168e847ee922)
Some group name or other conversation name will appear here, such as "回复" here. What appears here is neither my usual group nor my most recent group, and it seems to be just a random selection.

### Nekogram version

10.6.4

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by fxzxmicah** [comment]
@tehcneko 
![Screenshot_20240301_102412](https://github.com/Nekogram/Nekogram/assets/48860358/c36d29b0-c19d-40b6-86e7-9eee35c6458e)
Are you sure this is expected behavior?

**Comment by tehcneko** [comment]
this is probably some notification thingy from your OS

**Comment by fxzxmicah** [comment]
However, the official client does not have this situation, which is why I sent this issue.

**Comment by tehcneko** [comment]
Cannot reproduce the issue.
