### ISSUE TITLE
Please provide explanation for FORCING user to update for continue using application

### ISSUE THREAD

**Issue by Soneoylys** [Nekogram/Nekogram#69]
### Steps to reproduce

Install older version

### Expected behaviour

Choose if to skip or ignore update

### Actual behaviour

Not allowing further operation if not updated

### Nekogram version

10.5.0

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by Soneoylys** [comment]
Forcing update before access a chatting application especially known for data privacy is not acceptable
Although it's open sourced, but due to Google Play will post processing to binary, those version have different checksum as GitHub release version, after applying the forcing update there's a concern about data security.

Please consider remove forcing update or provide some explanation.

**Comment by Soneoylys** [comment]
![screenshot](https://github.com/Nekogram/Nekogram/assets/84897942/387083c3-951e-4a72-89cc-26812366943e)

Screenshot for reference

**Comment by tehcneko** [comment]
Just update

**Comment by tehcneko** [comment]
另外你在 Play 装的版本才会带你去 Play 更新，GitHub 或者频道里下的都是直接应用内更新或者带去 GitHub

**Comment by Soneoylys** [comment]
> Just update

It's not the part about “just update”, and I‘m not against updating stuff, but the security concern, I hope you understand that.

> 另外你在 Play 装的版本才会带你去 Play 更新，GitHub 或者频道里下的都是直接应用内更新或者带去 GitHub

Now this part is more acceptable, I‘ll just using GitHub release version and keep eyes on commit history then.

Still, I do think give user freedom to downgrade is something necessary, reason can vary even sometimes we don't like new UI (like Discord did to their mobile app) or system minimum version upgrade may happening anytime in future.

Thanks for replying anyways.
