### ISSUE TITLE
Add "Report Message" Function in Group

### ISSUE THREAD

**Issue by Makiras** [Nekogram/Nekogram#69]
## Describe
![image](https://user-images.githubusercontent.com/22570332/78119181-9bdb7f00-743a-11ea-91af-0b8a52b97854.png)

## What's more
It's possible to report a single picture message in PC client by right click, but not easy on touch device. Maybe add on picture's menu ? 

 (BTW, is there any difference in push service&FCM between neko and tele?  The push service seems to be unstable under the same configure in official client. I don't know if it is an illusion.)

**Comment by NekoInverter** [comment]
You can enable "Report" in NekoSettings

And I don't think there is any difference with push service
