### ISSUE TITLE
[Bug] Input box does not display text

### ISSUE THREAD

**Issue by HoratioShaw** [Nekogram/Nekogram#70]
### Steps to reproduce

Enter text in the input box or search bar

### Expected behaviour

Normal display text
![Screenshot_20240228_192033](https://github.com/Nekogram/Nekogram/assets/72498396/a961faba-bfe4-4c43-bc71-e5392f1d8d94)
（This is the official app.）

### Actual behaviour

Do not display text
![Screenshot_20240228_192116](https://github.com/Nekogram/Nekogram/assets/72498396/b93b2579-b7f6-4663-871e-f2895391a83f)
（This is Nekogram）

### Nekogram version

10.8.1 (44045)

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
https://t.me/NekoChatZH/65391

**Comment by HoratioShaw** [comment]
Can be displayed normally.

2024年2月29日 11:19，tehcneko ***@***.***>写道：

https://t.me/NekoChatZH/65391
