### ISSUE TITLE
[Feature Request] Detect, aggregate and display active voice/video chats grouped

### ISSUE THREAD

**Issue by demosthenez** [Nekogram/Nekogram#72]
### Is your feature request related to a problem?

Does discoverability of active voice chats count as a problem? Idk

### Describe the solution you'd like

Maybe a temporary but dynamically created and updated folder can be made in order to quickly see active voice or video group chats. I.e. you have 300 groups saved, 15 of them currently have active voice chats therefore you see those 15 groups listed in a dynamically update folder or a similar scoped view. 

### Additional context

I believe a feature like this could add a relatively new dimension to telegram usage/experience.  Not sure if telegram official would be interested in it or not.

**Comment by tehcneko** [comment]
you can find all groups with active voice chat in the calls section in drawer

**Comment by demosthenez** [comment]
> you can find all groups with active voice chat in the calls section in drawer

Well, that was fast.  Thanks for your quick work in implementing this.  All jokes aside, I never noticed this.  A little embarrassing.
