### ISSUE TITLE
Cannot find "save cache to private directory" option anymore

### ISSUE THREAD

**Issue by RememberTheAir** [Nekogram/Nekogram#73]
**Describe the bug**

I don't know if this should be considered a bug. Apparently the option is not there anymore, so I was wondering ti if has been removed on purpose

**To Reproduce**
1. Go to nekosettings
2. Search for the option to save cached medias in the private directory

**Expected behavior**
The option is still there

**Screenshots**
Can't find it anymore

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 9 (LineageOS 16)
 - Version 6.0.0

**Comment by RememberTheAir** [comment]
I just had a look at `nekoconfig.xml` in my shared prefs and it looks like `saveCacheToPrivateDirectory` is still there and set to "true". So I went into `/data/data/com.nekomimi.nekogram/files/Telegram` and noticed files are still indexed and cached here. So the option is actually enabled, but impossible to toggle?

**Comment by RememberTheAir** [comment]
Soooo does this mean the option is not going to be back? because I've just updated to 6.0.1.3 and files are still cached inside `/data/data/com.nekomimi.nekogram/files/Telegram`, despite the missing option

**Comment by NekoInverter** [comment]
> Soooo does this mean the option is not going to be back? Because I've just updated to 6.0.1.3 and files are still cached inside `/data/data/com.nekomimi.nekogram/files/Telegram`, despite the missing option

Tap on "Expetimental" and it will be back

**Comment by RememberTheAir** [comment]
Oh so there's a trick :) nice, thank you
