### ISSUE TITLE
[request] Add Muted chats to Folders (not only in Exclude filter)

### ISSUE THREAD

**Issue by KlausDevWalker** [Nekogram/Nekogram#77]
**Is your feature request related to a problem? Please describe.**
It was great that official Telegram finally added options to create folders. But they still put restrictions on what chats we can classify. 

**Describe the solution you'd like**
Though it's a minor problem, I wish I could put Muted chats as the main type for some of my folders.

**Describe alternatives you've considered**
--

**Additional context**
That way I couldn't have to go to "All Chats" to see the Muted chats mixed with Unmuted chats.

**Comment by NekoInverter** [comment]
You can ask Telegram for it :)

**Comment by KlausDevWalker** [comment]
I didn't get it... Is it not worth for Nekogram dev to implement it? Your answer was kinda rude, you know...

**Comment by SonicoXD1** [comment]
> I didn't get it... Is it not worth for Nekogram dev to implement it? Your answer was kinda rude, you know...

That'd probably require server side changes, as muted and unmuted chats are pretty much dynamic.
