### ISSUE TITLE
[Feature Request] Option to write a person by knowing their telegram id

### ISSUE THREAD

**Issue by ArmeF97** [Nekogram/Nekogram#78]
I am admin of some groups. I have id of some users I want to contact, but not their username. The API lets me write them so I can do it, but it will be wonderful if nekogram had that option, maybe with @id111111111 (for example)

**Comment by rikakomoe** [comment]
You can write at "Saved messages", and then click them

**Comment by ArmeF97** [comment]
![image](https://user-images.githubusercontent.com/6240983/79325292-39da4980-7f11-11ea-920e-dc2140c33445.png)

Does not work, it asks me in which app I want to open it
