### ISSUE TITLE
[FR] add an option to not download the next song

### ISSUE THREAD

**Issue by HitaloSama** [Nekogram/Nekogram#79]
Please add an option for Nekogram not to download the next song, by default when you listen to a song on a group or channel Telegram starts downloading the next, this sometimes is annoying especially when you do not want to listen to the next song, but it is there downloading and using more memory.

**Comment by SonicoXD1** [comment]
> Please add an option for Nekogram not to download the next song, by default when you listen to a song on a group or channel Telegram starts downloading the next, this sometimes is annoying especially when you do not want to listen to the next song, but it is there downloading and using more memory.

Simply tap on the music player and cancel the song download?

**Comment by NekoInverter** [comment]
![Screenshot_20200412-094104](https://user-images.githubusercontent.com/42698724/79058522-c4b50d00-7ca1-11ea-8392-01f0d436817d.png)
You can turn it off in auto-download settings
