### ISSUE TITLE
Background connection

### ISSUE THREAD

**Issue by ghost** [Nekogram/Nekogram#8]
### Is your feature request related to a problem?

I don't use Google Play Services, so the notifications are always delayed or will not show at all until I enter the app.

### Describe the solution you'd like

Many forks have the option to keep the app working in the background like ForkGram and Telegram FOSS, I hope you'll take a look at this.

Thank you for your time.

**Comment by ghost** [comment]
| Step 1 | Step 2 | Step 3 | Step 4 |
| ------- | ------- | ------- | ------- |
| ![Image 1](https://github.com/Nekogram/Nekogram/assets/114379310/e008bc39-5ef1-4ed4-8729-eada1154ff16) | ![Image 2](https://github.com/Nekogram/Nekogram/assets/114379310/a5ff9a5f-5614-4bd1-bedf-a2d624ac5e5c) | ![Image 3](https://github.com/Nekogram/Nekogram/assets/114379310/46bd7648-a61e-46ea-931c-83ca5ba4dc08) | ![Image 4](https://github.com/Nekogram/Nekogram/assets/114379310/c3d6429a-c5f7-4c65-9d18-bad9f30ec201) |

This is a very basic solution that will solve the problem now for people that are having this issue, until the developer will hopefully implement a better one.

**Comment by AlexandrKozlovskiy** [comment]
@tehcneko Please implement this feature. Because some devices havent google services and in this case it will be problems with authorization,because users cant get authorization code.

**Comment by tehcneko** [comment]
You can long press twice the version in settings, enable "Show a resident notification", then enable the two options in notification settings.

**Comment by AlexandrKozlovskiy** [comment]
@tehcneko But without google services users can't authorize in telegram account,because they can't get authorization code. It actual at least for official telegram.

**Comment by tehcneko** [comment]
it's not related, and google service is not required for getting auth code.

**Comment by ghost** [comment]
closing the issue because the method I showed before is doing the job very well for many weeks, reopening if anything goes wrong in the future.

**Comment by ani-dabrek** [comment]
> You can long press twice the version in settings, enable "Show a resident notification", then enable the two options in notification settings.

this worked for me, thanks!
