### ISSUE TITLE
[Feature Request] Please Add local premium 

### ISSUE THREAD

**Issue by anycall6779** [Nekogram/Nekogram#81]
### Is your feature request related to a problem?

As the title suggests, local premium features are added 

### Describe the solution you'd like

https://github.com/AyuGram/AyuGram4A

This is a local premium feature available here. 
Could you please add it?

**Comment by HitaloM** [comment]
They cannot do this because it breaks Telegram's Terms of Service, if they add functions that break the ToS, Nekogram's API keys could be banned and this would cause problems for the developer and users who would be unable to continue using the app.

https://core.telegram.org/api/terms
