### ISSUE TITLE
[Bug] Sidebar Icons Not Matching the Theme

### ISSUE THREAD

**Issue by Kyliekyler** [Nekogram/Nekogram#83]
### Steps to reproduce

1. Enable Auto-Night Mode Feature
2. Select System Default Theme
3. Wait Until it Enable the Light Theme on Morning

### Expected behaviour

It should follow the theme correctly like on the screenshot
![Screenshot_20240415-102342_Nekogram~3](https://github.com/Nekogram/Nekogram/assets/32427049/d55d143a-9bf5-4d0b-9314-7827e7a89469)

### Actual behaviour

The actual sidebar icon theme did not change accordingly until you restart the app and the cycle repeats again
![Screenshot_20240415-101644_Nekogram~2](https://github.com/Nekogram/Nekogram/assets/32427049/0f466104-5298-4298-9eec-ed15f1e4e2c5)

### Nekogram version

10.10.1

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
I'm pretty sure this is official bug
