### ISSUE TITLE
[BUG?] Translations not available

### ISSUE THREAD

**Issue by SonicoXD1** [Nekogram/Nekogram#83]
Translated strings are not always available in the app, even Chinese strings. After some app updates strings work, but after others they stop working. 
![Screenshot_20200514-131911_Nekogram](https://user-images.githubusercontent.com/61394886/81959236-8636a900-95e5-11ea-8c70-b477fa8bc530.jpg)
![Screenshot_20200514-131902_Nekogram](https://user-images.githubusercontent.com/61394886/81959248-88990300-95e5-11ea-8155-b4a87600367a.jpg)

Not really sure if this is a bug or intended.

**Comment by NekoInverter** [comment]
I don't know why and this never happened to me :(

**Comment by nekohasekai** [comment]
试试这个

```
android {
    bundle {
        language {
            enableSplit = false
        }
    }
}
```
