### ISSUE TITLE
Add support for adding a archive folder.

### ISSUE THREAD

**Issue by Akianonymus** [Nekogram/Nekogram#84]
Right now, we cannot make a folder which will just contain the archived chats, although excluding the archived chats are supported.

**Comment by NekoInverter** [comment]
I think it requires server side changes https://github.com/telegramdesktop/tdesktop/issues/7904

**Comment by KlausDevWalker** [comment]
Telegraph Messenger kind of has this feature, allowing have folder that won't be synced externally, like "All admin" folder (a folder that gather all.groups and channels that we created and/or we are admins.

**Comment by Akianonymus** [comment]
> Telegraph Messenger kind of has this feature, allowing have folder that won't be synced externally, like "All admin" folder (a folder that gather all.groups and channels that we created and/or we are admins.

@KlausDevWalker Neko do have a option to add all admin tabs.

![](https://telegra.ph/file/0129de617e3af65f49242.jpg)


Also, your suggestion may be a possible solution if it needs server side support.

**Comment by KlausDevWalker** [comment]
Thanks for the answer :)
