### ISSUE TITLE
[Suggestion] Add description for "Ignore blocked users in group"

### ISSUE THREAD

**Issue by groozchique** [Nekogram/Nekogram#85]
**Is your feature request related to a problem? Please describe.**
"Ignore blocked users in group" feature has a long name in Russian translation and I couldn't shorten it enough. For full understanding of what feature does, you have to read it through.

**Describe the solution you'd like**
If possible, add description this feature like for other features, for example, "Unlimited favored stickers"

**Additional context**
![IMG_20200518_125218_440](https://user-images.githubusercontent.com/28346376/82448217-18412480-9ab2-11ea-81c9-77ad2fe31dbc.jpg)

**Comment by NekoInverter** [comment]
This will be added in next update
