### ISSUE TITLE
[Feature Request] Allow No Quote Forwarding as a reply

### ISSUE THREAD

**Issue by HitaloM** [Nekogram/Nekogram#85]
### Is your feature request related to a problem?

It would be interesting to be able to forward messages without quote/caption as a reply to other messages.

### Describe the solution you'd like

Allow the forwarded message to be sent as a reply via the forward settings menu (shown in the video).

### Additional context

https://github.com/Nekogram/Nekogram/assets/40531911/053b7552-7715-49f2-ab76-161090ae4f6d

**Comment by tehcneko** [comment]
this isn't possible since we are using server api to forward messages
