### ISSUE TITLE
[Bug] Calls doesn't work

### ISSUE THREAD

**Issue by groozchique** [Nekogram/Nekogram#86]
**Describe the bug**
Pretty much the title, I can only add that it's same for incoming/outgoing calls. All permissible are given to the app. Calls also do work in TGX and official client.

**How to reproduce**
1. Call somebody

**Screenshots**
Video: https://gfycat.com/falsememorablebighorn
![Screenshot_20200527-030631828](https://user-images.githubusercontent.com/28346376/82961811-19e57d80-9fc7-11ea-9d75-55ceebc8bf75.jpg)

**Smartphone**
 - Device: Xiaomeme Poco F1
 - OS: Android 10
 - Version: V6.1.1.3 (1954)

**Comment by NekoInverter** [comment]
I've submitted a update with fix to Google Play, please wait a few hours then update to try calling again

**Comment by groozchique** [comment]
Fixed in V6.1.1.3 (1955), thanks!
