### ISSUE TITLE
[Feature Request] "Accept calls on this device" setting like in TelegramDesktop

### ISSUE THREAD

**Issue by bodqhrohro** [Nekogram/Nekogram#86]
### Is your feature request related to a problem?

Nekogram often has troubles making and accepting calls, so I have installed Telegram FOSS in parallel. But now, I have them both displaying the call popups, and Nekogram's one appears at the top, so I have to unlock the device and go to the drawer to pick the one of Telegram FOSS to accept the call, that's pretty annoying.

### Describe the solution you'd like

A setting so Nekogram won't attempt to accept calls at all.

**Comment by tehcneko** [comment]
You change that in Settings -> Devices, btw what is the trouble making calls?

**Comment by bodqhrohro** [comment]
> You change that in Settings -> Devices

Oh, okay, thanks!

> btw what is the trouble making calls?

IDK, they are usually stuck on key exchange stage and timeout after 20 seconds. I suspected there might be some problem with TURN servers, but tunneling through a proxy to a server with public IP also didn't help. I might provide some logs later.

**Comment by bodqhrohro** [comment]
[nekox.log](https://github.com/Nekogram/Nekogram/files/15141298/nekox.log)

**Comment by tehcneko** [comment]
this is repo for og nekogram

**Comment by bodqhrohro** [comment]
What is "og"?

**Comment by bodqhrohro** [comment]
Ah, got it, "original", I have Nekogram X.
