### ISSUE TITLE
[QUESTION] Color picker removed on 6.2.0

### ISSUE THREAD

**Issue by SonicoXD1** [Nekogram/Nekogram#87]
With Telegram 6.2 update, we got a revamped media editor, supporting animated stickers and editing videos. 
At the same time, the color picker vanished from Nekogram. Was this intentional, and is there any possibility of it coming back, at least for pics only? I'm no programmer, so I don't know how much the media editor changed, and what should be done to implement color picker again.

**Comment by NekoInverter** [comment]
It doesn't work well with the new editor and I don't have time to fix it 😞

**Comment by SonicoXD1** [comment]
It's okay, I'm not paying you or anything so no need to rush. It'd be great if you get it working again, otherwise, no need to worry! I'm leaving the issue open just in case, but feel free to close it if you want.
