### ISSUE TITLE
[Feature Request] Web File option in link preview

### ISSUE THREAD

**Issue by 0uros** [Nekogram/Nekogram#87]
### Is your feature request related to a problem?

It is not a problem in itself, but I think that you can have the option of sending web files directly from the preview link, since at least in my experience, it is necessary for it to be sent correctly and not show an error.

### Describe the solution you'd like

An option to directly send the file in the link (whether image, video or file) from the preview link (the only detail to take into account is how to mark whether it is sent as a file or not)

The one that is shown in this menu could be one more option in the Nekogram settings, I think it would make the option more accessible for those who use it (and who know it, since it is somewhat hidden imo)

### Additional context

![Screenshot_20240501_101959_Nekogram](https://github.com/Nekogram/Nekogram/assets/67289586/d3f45a6c-4f4d-45b7-b8b8-3beac2139981)
![Screenshot_20240501_102026_Nekogram](https://github.com/Nekogram/Nekogram/assets/67289586/77f4be41-bf8c-40c2-b0ee-9425faa209d5)

**Comment by tehcneko** [comment]
![Screenshot_2024-05-03-17-12-59-568_tw nekomimi nekogram beta](https://github.com/Nekogram/Nekogram/assets/88844448/214513f0-14f4-4331-acc4-4f50b0e0357f)
Something like this..?
Do we need to add original link to caption or not?
And after photo is sent, clear the input?

**Comment by 0uros** [comment]
> ![Screenshot_2024-05-03-17-12-59-568_tw nekomimi nekogram beta](https://private-user-images.githubusercontent.com/88844448/327706416-214513f0-14f4-4331-acc4-4f50b0e0357f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzUxMDgsIm5iZiI6MTcxNDczNDgwOCwicGF0aCI6Ii84ODg0NDQ0OC8zMjc3MDY0MTYtMjE0NTEzZjAtMTRmNC00MzMxLWFjYzQtNGY1MGIwZTAzNTdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDExMTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjVlNmE5YzI1NWQ0ZjVhNzBmYjljYWEwYzgwMGMzMDg4OWE0ZTE4MzM0MzY2NGVkZGM4MmM1OGNkMjY2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iFnlzKSKOp05BpPBDbArby-94KbWFVfaTttb_JwQTI) Something like this..? Do we need to add original link to caption or not? And after photo is sent, clear the input?

Yes, something like that would be great. Keep in mind that the function works with both videos and files too (PDFs I have used)

In the original function it allows you to send as a file, I don't know if it is worth taking it into account and that it was a submenu like the forwarding, or if it is already too much

Edit: the suggestion also has a compelling reason, and that is that to use the "send web file" function you need to have generated the preview, something that this menu does not do. What I do is paste it in the chat, wait for it to generate the preview and from there it works, one detail that I noticed is that videos work when you send them as a file

**Comment by tehcneko** [comment]
The photo in webpage preview, has already been compressed by Telegram server, so there is no point to include send as file.
And yes, videos and files are supported.

**Comment by 0uros** [comment]
In that case it's fine, sending as a file may be useful to someone because it is sent as a file and not because it is a file without compression. For a moment I thought about sending it like this by holding down the button.

Anyway, I saw that it was already implemented, thanks!
