### ISSUE TITLE
[Bug] nekogram crash

### ISSUE THREAD

**Issue by Xpremiumnetwork** [Nekogram/Nekogram#89]
### Steps to reproduce

[bugreport_I2201i_UP1A_231005_005_2024_05_04_13_50_49_dumpstate_log.txt](https://github.com/Nekogram/Nekogram/files/15209090/bugreport_I2201i_UP1A_231005_005_2024_05_04_13_50_49_dumpstate_log.txt)

### Expected behaviour

Should start as per usual and under the condition no personal data should be lost, chats should be visible

### Actual behaviour

The complete opposite, chats aren't visible with no visual of my current data being transparent. The app crashes on first try and upon second try, the account doesn't load.

https://github.com/Nekogram/Nekogram/assets/87702710/56d76a6d-6316-4221-bf87-a6dc331c75b9

### Nekogram version

10.12.0

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by PRO-2684** [comment]
Same for me, except that I can have a few seconds' glimpse of my contacts before it crashes

**Comment by wormuz** [comment]
Same problem here

adb logcat showing this
`05-05 01:58:33.098  1136  2291 E InputDispatcher: channel 'd769655 tw.nekomimi.nekogram/org.telegram.messenger.MusheenIcon (server)' ~ Channel is unrecoverably broken and will be disposed!
`
