### ISSUE TITLE
Still can see banned peoples in groups

### ISSUE THREAD

**Issue by WeFenFinit** [Nekogram/Nekogram#90]
**Describe the bug**
Messages of blocked users appear in the preview in the chat list and on reply

**To Reproduce**
Ban person, enable "ignore blocker users in group"

**Smartphone (please complete the following information):**
 - Device: LG G4c h522y
 - OS: Android 5.0.1
 - Version 6.2.0.1

**Comment by NekoInverter** [comment]
Works for me.

**Comment by WeFenFinit** [comment]
### Banned person:

![Untitled1](https://user-images.githubusercontent.com/22540805/84589407-191a6b80-ae50-11ea-80aa-3266f194f941.png)

### Can see his massages in chat list

![image](https://user-images.githubusercontent.com/22540805/84589466-71516d80-ae50-11ea-8a2a-1f18f458cbce.png)

### Same in Reply

![image](https://user-images.githubusercontent.com/22540805/84589500-b2e21880-ae50-11ea-8826-c66d544ade28.png)

**Comment by NekoInverter** [comment]
This is expected.
