### ISSUE TITLE
[Bug] Recorded video messages sped up, audio sync lacking

### ISSUE THREAD

**Issue by zeeall** [Nekogram/Nekogram#90]
### Steps to reproduce

1. Record Video Message
2. Play it back
3. Watch Video being laggy and sped up, blqck screen at the end, audio is okay and not stretched

### Expected behaviour

Video should play back in sync with audio and at 1x speed

### Actual behaviour

Video is sped up, jittery, and ending is just black screen (to fill space after video), audio behaviour is normal.

### Nekogram version

v10.12.0 (4711) arm64-V8a

### Android version

14

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
#91
