### ISSUE TITLE
Crush after forcing tablet mode

### ISSUE THREAD

**Issue by WeFenFinit** [Nekogram/Nekogram#91]
**Describe the bug**
App crushes after forcing tablet mode 

**To Reproduce**
1. Go to 'Settings -> Neko Settings -> General'
2. Click on 'Force tablet mode'
3. Trying to restart app
4. Crush

**Smartphone**
 - Device: LG G4c h522y
 - OS: 5.0.1
 - Version: 6.2.0.1

**Comment by WeFenFinit** [comment]
logcat:
```
E/AndroidRuntime(11288): Process: tw.nekomimi.nekogram, PID: 11288
E/AndroidRuntime(11288): java.lang.RuntimeException: Unable to pause activity {tw.nekomimi.nekogram/org.telegram.ui.LaunchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.telegram.ui.ActionBar.ActionBarLayout.onPause()' on a null object reference
```

**Comment by NekoInverter** [comment]
work as expected

**Comment by WeFenFinit** [comment]
![image](https://user-images.githubusercontent.com/22540805/84594922-08c9b700-ae77-11ea-9423-b3d984b3b351.png)
