### ISSUE TITLE
[Feature Request] Alternative to GSF for notifications

### ISSUE THREAD

**Issue by SpringsTS** [Nekogram/Nekogram#93]
### Is your feature request related to a problem?

Nekogram, like Telegram official client, relies on Google Services Framework (GSF) for notifications.
On google-free system, even with microG installed and set up for Push Messaging, notifications do not work: they stop appearing a while after application goes in background.

### Describe the solution you'd like

Nekogram X and Forkgram have their notification system trough a permanent notification.
A solution could be to implement the same system for non-Google systems.

### Additional context

On Android ≤13, I could get notification work by unregistering Nekogram from micro'G Push Message settings, and disabling battery optimisation for the app.
On Android 14, this workaround does not work anymore, even when I activate resident notification in debug menu.

**Comment by tehcneko** [comment]
the resident notification option in debug is for the notification, if it doesn't work, there is nothing else we can do
