### ISSUE TITLE
Feature Request: Use SD card to store cache and downloads 

### ISSUE THREAD

**Issue by Ryder17z** [Nekogram/Nekogram#93]
Please.

**Comment by NekoInverter** [comment]
![Screenshot_20200617-093943](https://user-images.githubusercontent.com/42698724/84845154-857ab200-b07e-11ea-8e80-9d75484c6f96.png)
Turn this off

**Comment by 0xCA** [comment]
I guess the request was the opposite: to store the cache on **external sd** to save internal space

**Comment by Ryder17z** [comment]
> 
> 
> I guess the request was the opposite: to store the cache on **external sd** to save internal space

yes
