### ISSUE TITLE
System emoji option doesn't work properly

### ISSUE THREAD

**Issue by muznyo** [Nekogram/Nekogram#96]
Some emojis e.g. 🅰️🅱️🅾️ turn into black, so they don't follow the system emojis

I expected them to follow the system so in my point of view they will be red boxes with white letters.

Also i have a black theme so i don't see those emojis, because those emojis turn black.

Xiaomi Redmi Note 5A, android 10

![Screenshot_20200701-154209~2.jpg](https://user-images.githubusercontent.com/24987471/86252056-feb3f200-bbb2-11ea-81e5-24ea97c99376.jpg)

![Screenshot_20200701-154320~2.jpg](https://user-images.githubusercontent.com/24987471/86252104-125f5880-bbb3-11ea-8e8f-58de6d96e6f6.jpg)

![Screenshot_20200701-154159~2.jpg](https://user-images.githubusercontent.com/24987471/86252122-17bca300-bbb3-11ea-80e2-859af1f43e26.jpg)

**Comment by NekoInverter** [comment]
What do these emojis look like elsewhere?

**Comment by muznyo** [comment]
They look like this:

![Screenshot_20200701-154320~2.jpg](https://user-images.githubusercontent.com/24987471/86354449-5dd43e00-bc69-11ea-9d35-f96e37e7162b.jpg)

**Comment by NekoInverter** [comment]
Probably system issue :thinking:
