### ISSUE TITLE
[Bug] Black screen at the end of video message

### ISSUE THREAD

**Issue by Phistan** [Nekogram/Nekogram#98]
### Steps to reproduce

 1.   Record and send video message
 2.   Play it
 3.   Video is unsync to audio and ends with black screen

### Expected behaviour

Video should play normally

### Actual behaviour

Video is unsync to audio and ens with black screen

### Nekogram version

10.13.1 (4845) arm64-v8a

### Android version

13

### Reproducible requirement

- [X] I've test on official Telegram Android client and this bug is only reproducible on Nekogram.

**Comment by tehcneko** [comment]
#91
