### ISSUE TITLE
Show a "Stories" tab when hiding stories

### ISSUE THREAD

**Issue by lolouthefox** [Nekogram/Nekogram#99]
### Is your feature request related to a problem?

When hiding stories there is no more way to access stories. The goal of the feature is to make the home screen less clugged and/or hide personal information on app launch.

### Describe the solution you'd like

A simple solution would be being able to open the stories directly from the side menu (burger menu on the top left corner). This would open the stories by opening the first one first, and not caring about wether you read it or not.
This feature would enable us to still access stories when stories are hidden on home screen, and keep up with our friends; While still keep the simplistic nature of Nekogram too.

**Comment by tehcneko** [comment]
You can still access stories from your contacts in the contacts page by clicking on the stories cricle

**Comment by lolouthefox** [comment]
Yes but you cannot post or see Stories from groups when they are not shown on the home page...

**Comment by tehcneko** [comment]
> Yes but you cannot post or see Stories from groups when they are not shown on the home page...

Stories from groups can still be accessed by clicking on the profile photo, posting stories will be allowed in next version.
